### ISSUE TITLE
[doc] NITF file format support

### ISSUE THREAD

**Issue by learning4life** [MISS3D/s2p#123]
Based on https://github.com/MISS3D/s2p/pull/55 a workaround to enable NITF files likely already exists? 

If not, GDAL also supports NITF and if the RPC00B (or RPC00A) is available, it is used to report RPC metadata, based on http://www.gdal.org/frmt_nitf.html .  

Any information in this area is very welcome.

**Comment by gfacciol** [comment]
With PR #145, the NITF RPCs should work. Just don't specify the rpc filed in the json, and GDAL will recover the RPC from the NITF.
