### ISSUE TITLE
Bad version of GDAL in Dockerfile

### ISSUE THREAD

**Issue by GwennaelM** [MISS3D/s2p#135]
It seems the default version of GDAL (1.11.3) in ubuntu 16.04 is incompatible with s2p, at least because the "-vrtnodata nan" parameter of gdalbuildvrt is unknown before GDAL 1.11.5.
This parameter is used in "global_dsm" method of s2p.py:
`common.run("gdalbuildvrt -vrtnodata nan -input_file_list %s %s" [...]`

If confirmed, it may be best to recompile a newer version of GDAL in Dockerfile (the README file recommandes GDAL 2.1.0).

Related issue in GDAL bucktracker: https://trac.osgeo.org/gdal/ticket/6495

**Comment by learning4life** [comment]
I have also confirmed that the docker image has an outdated GDAL version.

GDAL 2.1 is available for Ubuntu 16.04 from the ubuntugis-stable PPA:

https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa

**Comment by learning4life** [comment]
I made the following input to the `dockerfile` with GDAL 2.1, cmake, lxml and moved from "github.com/carlodef/s2p" to "github.com/MISS3D/s2p"

I tested the build by running the `dockerfile` using the `docker build` command:
`sudo docker build -t s2p/gdal:2.1 .`
`sudo docker run s2p/gdal:2.1 python s2p.py testdata/input_pair/config.json`

Dockerfile:
```
# docker for s2p
# Carlo de Franchis <carlodef@gmail.com>

FROM ubuntu:16.04
MAINTAINER Carlo de Franchis <carlodef@gmail.com>
ARG DEBIAN_FRONTEND=noninteractive # https://goo.gl/aypXVx
RUN apt-get update && apt-get install -y \
    build-essential \
    geographiclib-tools \
    git \
    libfftw3-dev \
    libgdal-dev \
    libgeographic-dev \
    libgeotiff-dev \
    libtiff5-dev \
    python \
    python-numpy \
    python-pip \
    cmake \
    software-properties-common \
    python-software-properties
RUN pip install -U pip
RUN pip install utm bs4 lxml requests

# Install GDAL 2.x from ubuntugis-stable
RUN apt-get install dialog apt-utils -y
RUN add-apt-repository ppa:ubuntugis/ppa -y 
RUN apt-get update && apt-get install -y \
    gdal-bin \
    python-gdal

# Install s2p from MISS3D/s2p
RUN git clone https://github.com/MISS3D/s2p.git --recursive
RUN cd s2p && make all

WORKDIR /s2p
```

**Comment by gfacciol** [comment]
Thanks @GwennaelM @learning4life I've merged the proposed fix.
