### ISSUE TITLE
Code base which works on MacOS?

### ISSUE THREAD

**Issue by rohun-tripathi** [MISS3D/s2p#142]
Hi, the README describes the dependencies to run the code base on a (Ubuntu 16.04).

Is this code tested for a MacOS? Is there a parallel code base or another pipeline for the same?

Thanks

**Comment by carlodef** [comment]
Hi,

Yes, the code is tested on macOS: https://github.com/MISS3D/s2p/blob/master/.travis.yml#L15

Feel free to report any issues you get when running it.
