### ISSUE TITLE
Guys, excellent job, but how to run the program?

### ISSUE THREAD

**Issue by hbzhang** [MISS3D/s2p#144]
Guys, I am able to compile the program, but I am stuck with how to make the first test run. Can anyone update the readme a bit of more to show how to make the first test run in order to see a workable demo? Thanks!!

**Comment by carlodef** [comment]
https://github.com/MISS3D/s2p#usage

**Comment by hbzhang** [comment]
Thanks for the quick response. I just executed the command, but get this error:
computing global DSM...

RUN: gdalbuildvrt -vrtnodata nan -input_file_list /home/hbzhang/s2p/testdata/input_pair/../../testoutput/output_pair/gdalbuildvrt_input_file_list.txt /home/hbzhang/s2p/testdata/input_pair/../../testoutput/output_pair/dsm.vrt
ERROR 5: Invalid -vrtnodata value
Traceback (most recent call last):
  File "s2p.py", line 831, in <module>
    main(user_cfg, args.step)
  File "s2p.py", line 756, in main
    global_dsm(tiles)
  File "s2p.py", line 619, in global_dsm
    out_dsm_vrt))
  File "/home/hbzhang/s2p/s2plib/common.py", line 97, in run
    e.output})
s2plib.common.RunFailure: {'environment': {'LESSOPEN': '| /usr/bin/lesspipe %s', 'SSH_CLIENT': '192.168.1.12 65531 22', 'LOGNAME': 'hbzhang', 'USER': 'hbzhang', 'PATH': '/home/hbzhang/s2p/bin:/home/hbzhang/bin:/home/hbzhang/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'HOME': '/home/hbzhang', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'SHLVL': '1', 'XDG_RUNTIME_DIR': '/run/user/1000', 'XDG_SESSION_ID': '2', '_': '/usr/bin/python', 'SSH_CONNECTION': '192.168.1.12 65531 192.168.1.28 22', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'SSH_TTY': '/dev/pts/0', 'OLDPWD': '/home/hbzhang/s2p/bin', 'XDG_DATA_DIRS': '/usr/local/share:/usr/share:/var/lib/snapd/desktop', 'PWD': '/home/hbzhang/s2p', 'MAIL': '/var/mail/hbzhang', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'}, 'output': None, 'command': u'gdalbuildvrt -vrtnodata nan -input_file_list /home/hbzhang/s2p/testdata/input_pair/../../testoutput/output_pair/gdalbuildvrt_input_file_list.txt /home/hbzhang/s2p/testdata/input_pair/../../testoutput/output_pair/dsm.vrt'}

**Comment by carlodef** [comment]
https://github.com/MISS3D/s2p#dependencies

> gdal version must be 2.1.0 or newer

**Comment by hbzhang** [comment]
Thanks for quick guide!

I am able to run the code. In testoutput folder/outputpair subfolder, it generates some files. But I have not sufficient capacity to interpret those results and correspond it back to your paper. They seem different. 

So, is there anyone that I can generate the 3D images similar to your listed paper references? They are looking really good and very intuitive for me to understand your project.

Thank you!!
