### ISSUE TITLE
min_max_heights_from_bbx  - not a sequence error with TransformPoints

### ISSUE THREAD

**Issue by wdixon** [MISS3D/s2p#161]
When using exogenous_dem option - the function min_max_heights_from_bbx calls

x_im_proj, y_im_proj, __ = (zip(*lonlat_to_im.TransformPoints(lonlatalt)))
however lonlatalt is not a sequence as TransformPoints is expecting.

Instead changed to:
    li = [a for a in lonlatalt]
    x_im_proj, y_im_proj, __ = (zip(*lonlat_to_im.TransformPoints(li)))

**Comment by wdixon** [comment]
PR submitted

**Comment by carlodef** [comment]
Fixed by PR #162. Thanks!
