### ISSUE TITLE
Provided Preview image not found

### ISSUE THREAD

**Issue by AudreyCh** [MISS3D/s2p#164]
Hi, 

I tried to run S2p on a TriStereo Pleiade Image. Unfortunately, the processing of the entire image is way too greedy with RAM, CPU and disk space. 

The solution would be to run the script on a ROI of the image. The "README" explains that if none of the ROI or full_img flags are present, I can provide a preview of the main image and select the ROI on this image. 

My "image" dictionary with be define as: 

```
"images" : [
    { "prv" : "PRV_02.JPG", 
      "img" : "IMG_02.tif",
      "rpc" : "RPC_02.xml" },
    { "img" : "IMG_01.tif",
      "rpc" : "RPC_01.xml" },
    { "img" : "IMG_03.tif",
      "rpc" : "RPC_03.xml"}
    ]
```

But the script ends with this error:

```
Traceback (most recent call last):
  File "s2p.py", line 809, in <module>
    main(user_cfg, args.step)
  File "s2p.py", line 666, in main
    initialization.build_cfg(user_cfg)
  File "/s2p/s2plib/initialization.py", line 110, in build_cfg
    check_parameters(user_cfg)
  File "/s2p/s2plib/initialization.py", line 78, in check_parameters
    d['images'][0]['prv'])
  File "/s2p/s2plib/common.py", line 708, in get_roi_coordinates
    nc_preview, nr_preview = image_size_gdal(preview)[:2]
  File "/s2p/s2plib/common.py", line 172, in image_size_gdal
    f = gdal.Open(im)
  File "/usr/lib/python2.7/dist-packages/osgeo/gdal.py", line 2943, in Open
    return _gdal.Open(*args)
RuntimeError: PRV_02.JPG: No such file or directory
```

The PRV_02.JPG really exists and is located in the same directory as the image. What do I do wrong with this "prv" key?

Do you have an idea of how much disk space will be enough to process the whole image (around 220 km²)?

Thanks in advance for your help!

**Comment by gfacciol** [comment]
* Remove the   "prv" :  key from the configuration, it's optional. 
* About the disk space it depends on the resolution of your satellite image. To give you an idea, in order to process a worldview2 image pair of 4000x4000 pixel each, it takes about 2Gb.
