### ISSUE TITLE
Using s2p framework with own stereo matching algorithm

### ISSUE THREAD

**Issue by thedodo** [MISS3D/s2p#165]
Hi!

I have the following problem: I want to use the s2p framework with my own matching algorithm.
The problematic part is that this matching algorithm that I want to try does not work with negative disparities.
So the rectification that is done in the framework (disparities centered around 0) does not work for me.

I have already located that in the 3rdparty folder there is a "hack" for this disparity convention for the SGM 2002 method (hirschmuller02) in subpix.sh, however at least as of now I do not get this code, especially as it uses other code of the framework such as imprintf and iion. 

Also when I tried to use this matching algorithm with the included testdata input_pair/config.json:
  "matching_algorithm" : "hirschmuller02"

It did not work (does not find subpix.sh). I have already downloaded and compiled boofcv with ant in the 3rdparty/stereo_hirschmueller_2002 folder.

Maybe someone can help me to get this to work and/or elaborate on this disparity "hack" so I could try this "hack" on my own.

best regards, Dominik

**Comment by thedodo** [comment]
It seems that this repository is no longer maintained by the authors.

However if someone in the future may have the same issue: I found that a purely positive disparity rectification is already implemented.
You simply have to pass the flag 'positive' to the function register_horizontally_translation() (in s2plib/rectification.py)

**Comment by carlodef** [comment]
Hello @thedodo, sorry for overlooking your issue, and thank you very much for your messages. We may not be very responsive on all issues but the repository is still maintained and updated with new features.

Indeed a purely positive disparity rectification is implemented in the the function `s2plib.rectification.register_horizontally_translation()`.
