### ISSUE TITLE
Hello, thank you for your code. I have some doubts. Hope to get your help.

### ISSUE THREAD

**Issue by lystudent** [MISS3D/s2p#166]
Hello, thank you very much for your code. In the code you provided, I found that files like rpc_01.xml were used. Is this document the data provided by the competition? Or is it extracted from other data? And what data are your satellite sensors using? Do you have a download address? Hope to get your help.

**Comment by transform39** [comment]
I also have the problem of changing "rpc_01.txt" file into "rpc_01.xml" file. Do you have any good solution?

**Comment by gfacciol** [comment]
The format of the rpc is detected independently of its extension, so using .txt should work. 
Moreover, if your images are Geotiff or NITF the rpc can be extracted automatically from the images, for that you should remove the rpc fields from the config.
