### ISSUE TITLE
How to fill the holes in DSM.tif?

### ISSUE THREAD

**Issue by lionlai1989** [MISS3D/s2p#181]
I am running the pleiades images, and the process can run successfully. But the output DSM has too many holes in it. Below it the result. (White points means no data)
<img width="674" alt="screen shot 2018-11-26 at 5 49 17 pm" src="https://user-images.githubusercontent.com/5163329/49029237-6e2a5a00-f1a4-11e8-98f8-39dddbf1117c.png">
How to fill the holes in DSM or it's abnormal result which means I did something wrong?

Any help would be appreciated.
Thank you.

**Comment by thedodo** [comment]
Of course no data values can always happen, it does not mean that the output is wrong (for instance through self-occlusion). 
Without having the image pair that was used it is hard to say if this is wrong or not. 
Does the 3D model make sense if you view it e.g. in QT Reader? 

As to how to get rid of them: You can use any available computer vision tool, e.g. interpolate non-existing data using neighborhood information or use convolutions (for instance bilateral/guided filter) either on the disparity map or on the height map directly.

best regards

**Comment by dyoussef** [comment]
The parameter ```dsm_radius``` allows you to interpolate the small holes.
Many small holes can appear when the sensor resolution and the ```dsm_resolution``` are similar.

**Comment by dyoussef** [comment]
The parameter ```dsm_radius``` allows you to interpolate the small holes.
Many small holes can appear when the sensor resolution and the ```dsm_resolution``` are similar.

Regards

**Comment by lionlai1989** [comment]
Thank you. I change the `dsm_radius` from 0 to 1, and it works.
