### ISSUE TITLE
Dockerfile not comment correctly and should add apt-get install unzip

### ISSUE THREAD

**Issue by lionlai1989** [MISS3D/s2p#184]
Hi guys:
I found an incorrect comment in Dockerfile.
The following line
`ARG DEBIAN_FRONTEND=noninteractive # https://goo.gl/aypXVx`
The comment about will make my following command fails.
` sudo docker build -t s2p/gdal:2.1 .`
with the error.
`Error response from daemon: Dockerfile parse error line 6: ARG requires exactly one argument`

Another issue is that it would be better if Dockerfile has an additional line.
`RUN apt-get install unzip`
If not, there will be the following error.
`mv lsd_1.6.zip 3rdparty
unzip -o 3rdparty/lsd_1.6.zip -d 3rdparty
make: unzip: Command not found
make: *** [lsd] Error 127
makefile:64: recipe for target 'lsd' failed
The command '/bin/sh -c cd s2p && make all' returned a non-zero code: 2`

**Comment by gfacciol** [comment]
Thanks @lionlai1989 !  
I just fixed it. 
Let us know if you find another issue.
