### ISSUE TITLE
how to use Digital Globe's (DG) stereo-pair images with S2P

### ISSUE THREAD

**Issue by echarus** [MISS3D/s2p#215]
We are considering to use Digital Globe's (DG) stereo-pair images with S2P. However, DG's stereo-pair images have RPB files only and these don't contain the inverse model RPC coefficients in them (only forward model RPC coefficients are available). Since S2P requires both forward and inverse model RPC coefficients, we are looking for a way to estimate the inverse model RPC coefficients. Is there any third party tool that we can use to estimate the inverse model RPC coefficients, or any suggestion about how to use DG's stereo pair images with S2P?

**Comment by gfacciol** [comment]
S2P does not neeed the inverse model. So you can use DG imagery without
issues.
