### ISSUE TITLE
Failed building wheel for s2p

### ISSUE THREAD

**Issue by valeriodeluca** [MISS3D/s2p#216]
Hi @carlodef 
Great project! :)
During installation I get:
"Failed building wheel for s2p"
I have ubuntu 18.04.2.
Thanks
Valerio

**Comment by gfacciol** [comment]
Hi,
can you re-run the installation with:
    pip3 install s2p --user --verbose

I guess that you're missing some development tools needed for the wheel
compilation:
    https://github.com/cmla/s2p#other-dependencies-geographiclib-fftw

best,
-

**Comment by valeriodeluca** [comment]
Thank you @gfacciol,
Now the install gone right, but I get ImportError: No module named s2p both in python and python3.
Thank you for your time
best
Valerio

**Comment by valeriodeluca** [comment]
It seems that with ubuntu 18.04.3 no import error.
Thanks
Best
Valerio
