### ISSUE TITLE
Compiling binaries is unsuccessful

### ISSUE THREAD

**Issue by learning4life** [MISS3D/s2p#37]
Compiling binaries using ‘make’ results in “Could not find GDAL” (error code below)?
_Please note that compiling binaries is new to me._

**Dependencies applied:**
- cmake, libtiff, libpng, libjpeg, libfftw3, libgeotiff, gdal, and the Python module utm.
- gdal version is 1.10.1, released 2013/08/26

I also tried to manually download gdal-1.10.1.tar.gz  to 3rdparty and install following the description under “GDAL >= 1.10”. 
Dose this method require gdal to be copied to the bin folder manually?

I have root access and using LMDE2 and Debian 8.6 systems. 

**Error code resulting from the command 'make'** 
mkdir -p bin/build_homography
cd bin/build_homography; cmake ../../c/homography; make
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find GDAL (missing: GDAL_LIBRARY GDAL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.0/Modules/FindGDAL.cmake:116 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:34 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/dem/local/bin/build_homography/CMakeFiles/CMakeOutput.log".
make[1]: Entering directory '/home/dem/local/bin/build_homography'
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory '/home/dem/local/bin/build_homography'
makefile:53: recipe for target 'homography' failed
make: *** [homography] Error 2

**Comment by dyoussef** [comment]
Hello learning4life,
Can you try to compile specifying the location of GDAL with the environment variable "GDAL_DIR" (export GDAL_DIR=)? (https://cmake.org/cmake/help/v3.0/module/FindGDAL.html).

**Comment by learning4life** [comment]
Hello David, thank you for your fast respond. I am very impressed with your results with this project!

When I upgrade GDAL to 1.11.3 on my other system I get the following error using the master branch: 
_g++ -g -O3 -I 3rdparty/GeographicLib-1.32/include -I 3rdparty/GeographicLib-1.32/man 3rdparty/GeographicLib-1.32/tools/CartConvert.cpp 3rdparty/GeographicLib-1.32/src/DMS.cpp 3rdparty/GeographicLib-1.32/src/Geocentric.cpp 3rdparty/GeographicLib-1.32/src/LocalCartesian.cpp -o bin/CartConvert
make: g++: Command not found
makefile:39: recipe for target 'bin/CartConvert' failed
make: *** [bin/CartConvert] Error 127_

And when using your develop branch I end with:
_make[2]: Leaving directory '/home/dem/local2/3rdparty/tiff-4.0.4beta/libtiff'
Makefile:537: recipe for target 'install-recursive' failed
make[1]: *** [install-recursive] Error 1
make[1]: Leaving directory '/home/dem/local2/3rdparty/tiff-4.0.4beta'
makefile:37: recipe for target '3rdparty/tiff-4.0.4beta/lib/libtiff.a' failed
make: *** [3rdparty/tiff-4.0.4beta/lib/libtiff.a] Error 2_

Not sure if it is the GDAL problem anymore?

**Comment by dyoussef** [comment]
I think you must install g++ (https://ubuntuforums.org/showthread.php?t=1464768) to compile s2p master branch. Concerning the develop branch, we will remove unneeded libtiff sources soon so you will not need to compile libtiff.

**Comment by learning4life** [comment]
Perfect David, by adding "sudo apt-get install build-essential g++" I was able to proceed.

The missing GDAL was fixed by installing "sudo apt-get install libgdal1-dev"

Both the s2p master and develop starts to compile, but stops with the same error:
- Cannot find source file:  pickopt.c

**Error code**
-- cd bin/build_homography; cmake -D CMAKE_BUILD_TYPE=Release ../../c/homography; make
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Try OpenMP C flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Try OpenMP CXX flag = [-fopenmp]
-- Performing Test OpenMP_FLAG_DETECTED
-- Performing Test OpenMP_FLAG_DETECTED - Success
-- Found OpenMP: -fopenmp  
-- Found GDAL: /usr/lib/libgdal.so  
-- Configuring done
CMake Error at CMakeLists.txt:59 (add_executable):
  Cannot find source file:

    pickopt.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


CMake Error: CMake can not determine linker language for target: homography
CMake Error: Cannot determine link language for target "homography".
-- Generating done
-- Build files have been written to: /home/r61/local2/bin/build_homography
make[1]: Entering directory '/home/r61/local2/bin/build_homography'
make[2]: Entering directory '/home/r61/local2/bin/build_homography'
make[3]: Entering directory '/home/r61/local2/bin/build_homography'
Scanning dependencies of target homography
make[3]: Leaving directory '/home/r61/local2/bin/build_homography'
make[3]: Entering directory '/home/r61/local2/bin/build_homography'
make[3]: *** No rule to make target 'CMakeFiles/homography.dir/build'.  Stop.
make[3]: Leaving directory '/home/r61/local2/bin/build_homography'
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/homography.dir/all' failed
make[2]: *** [CMakeFiles/homography.dir/all] Error 2
make[2]: Leaving directory '/home/r61/local2/bin/build_homography'
Makefile:83: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/r61/local2/bin/build_homography'
makefile:68: recipe for target 'homography' failed
make: *** [homography] Error 2

**Comment by dyoussef** [comment]
c/homography/pickopt.c is a symbolic link to c/pickopt.c.
Can you check whether the symlink exists or not?

**Comment by learning4life** [comment]
True, for a unknown reason the symlink is not created when s2p-master is unzipped into a folder like ~/local. When using ~/Documents/s2p-master the symlink is working on both my systems.

But when running make it stops prematurely at
"cp 3rdparty/mgm/mgm bin" 

**make output**
~/Documents/s2p-master $ make
mkdir -p bin/build_homography
cd bin/build_homography; cmake ../../c/homography; make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dem/Documents/s2p-master/bin/build_homography
make[1]: Entering directory '/home/dem/Documents/s2p-master/bin/build_homography'
make[2]: Entering directory '/home/dem/Documents/s2p-master/bin/build_homography'
make[3]: Entering directory '/home/dem/Documents/s2p-master/bin/build_homography'
make[3]: Leaving directory '/home/dem/Documents/s2p-master/bin/build_homography'
[100%] Built target homography
make[2]: Leaving directory '/home/dem/Documents/s2p-master/bin/build_homography'
make[1]: Leaving directory '/home/dem/Documents/s2p-master/bin/build_homography'
cp bin/build_homography/homography bin
mkdir -p bin/build_sift
cd bin/build_sift; cmake ../../c/sift; make
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dem/Documents/s2p-master/bin/build_sift
make[1]: Entering directory '/home/dem/Documents/s2p-master/bin/build_sift'
make[2]: Entering directory '/home/dem/Documents/s2p-master/bin/build_sift'
make[3]: Entering directory '/home/dem/Documents/s2p-master/bin/build_sift'
make[3]: Leaving directory '/home/dem/Documents/s2p-master/bin/build_sift'
[ 38%] Built target matching
make[3]: Entering directory '/home/dem/Documents/s2p-master/bin/build_sift'
make[3]: Leaving directory '/home/dem/Documents/s2p-master/bin/build_sift'
[100%] Built target sift_roi
make[2]: Leaving directory '/home/dem/Documents/s2p-master/bin/build_sift'
make[1]: Leaving directory '/home/dem/Documents/s2p-master/bin/build_sift'
cp bin/build_sift/sift_roi bin
cp bin/build_sift/matching bin
cc -std=c99 -g -O3 -DNDEBUG -DDONT_USE_TEST_MAIN c/plambda.c c/iio.o -o bin/plambda -lz -ltiff -lpng -ljpeg -lm
c/iio.o: In function `iio_save_image_as_tiff_smarter':
/home/dem/Documents/s2p-master/c/iio.c:2326: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
cd 3rdparty/mgm; make
make[1]: Entering directory '/home/dem/Documents/s2p-master/3rdparty/mgm'
gcc -std=c99 -O3 -DNDEBUG -ffast-math -fopenmp -DIIO_ABORT_ON_ERROR -Wno-deprecated-declarations -c iio/iio.c -o iio.o
g++ -O3 -DNDEBUG -ffast-math -fopenmp -Iiio -Icommon -DTEST_MAIN mgm.cc img.cc point.cc iio.o -o mgm -lpng -ltiff -ljpeg
iio.o: In function `iio_save_image_as_tiff_smarter':
iio.c:(.text+0x3aa7): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
make[1]: Leaving directory '/home/dem/Documents/s2p-master/3rdparty/mgm'
cp 3rdparty/mgm/mgm bin

**Comment by carlodef** [comment]
Hi Thomas,
I don't see any error in you output. The compilation succeeded.

**Comment by carlodef** [comment]
Hi Thomas, if you're still stuck with compilation issues you may try the s2p docker image which is available here: https://hub.docker.com/r/carlodef/s2p/

**Comment by learning4life** [comment]
Hi Carlo, thank you for your follow-up. I can confirm that your latest update has solved my compilation issue. Nice addition with the s2p docker image.
I now feel confident applying your s2p to my dataset in my master thesis project!
Kind regards 
Thomas
