### ISSUE TITLE
The s2p licence

### ISSUE THREAD

**Issue by oleg-alexandrov** [MISS3D/s2p#57]
I see that s2p is licenced under AGPL 3.0. 

I am sure that you folks thought very hard about it, and there are many good things to be said about it. I, like you, believe that software should reach the largest amount of people, and have the hugest impact, changing the world with high quality tool.

Yet, if that is the goal, I will argue that AGPL is in fact not the right license. I know the worries, that somebody will steal the code and incorporate it into their proprietary solution, etc, etc.

Yet, in fact, counter-intuitively, GPL-related licences, of which I used to be a big fan, are actually quite bad at festering innovation and achieving their goals. GPL is considered poison. It messes up everything it touches. Companies, and even government agencies, like NASA Ames where I work, don't want to have anything to do with GPL. 

The trend these days are towards more permissive licences, like Apache, BSD, and MIT. Look for example at OpenCV, ROS, Python source code, Android, etc. 

I am sure you know all these things. And really, since S2P is a collection of standalone tools, one can still easily use them from a new glue Python software while bypassing the GPL constraint. Yet, I would still like to ask the question, why AGPL and not something more liberal which may foster more cooperation?

**Comment by carlodef** [comment]
Hi Oleg,
Thank you for your interest in s2p. The question of switching from AGPL to a more permissive licence was already discussed internally a few months ago. We agreed on moving to a BSD-like licence but we have to wait for the formal agreements of our institutions (CMLA and CNES).

**Comment by oleg-alexandrov** [comment]
This is great to hear.
