### ISSUE TITLE
Compilation error tvl1flow_3 (osx)

### ISSUE THREAD

**Issue by dyoussef** [MISS3D/s2p#80]
When compiling tvl1flow_3 under osx, the console log shows the following error :
clang: error: unsupported option '-fopenmp'

**Comment by mnhrdt** [comment]
as a short-term solution you can simply remove this option from the makefile

**Comment by gfacciol** [comment]
Or you can just fix the problem by adding the following line to the makefile


# use OpenMP only if not clang
ifeq ($(shell $(CC) -v 2>&1 | grep -c "clang"), 0)
CFLAGS+=-fopenmp
endif

**Comment by mnhrdt** [comment]
There are other things to change (hide the omp_ calls, etc)

I'm putting all these things in this repo, it can eventually become a module of s2p: https://github.com/mnhrdt/tvl1flow/

**Comment by dyoussef** [comment]
@mnhrdt : if you make the pull request with tv1flow as submodule, I approve it

**Comment by mnhrdt** [comment]
PR #81 fixes this problem (because the travis test passes on osx).
