### ISSUE TITLE
runtime error in gdalbuildvrt

### ISSUE THREAD

**Issue by mnhrdt** [MISS3D/s2p#83]
This is apparently a non-deterministic error that happens from time to time.  When running "make test" on a debian 7.7:

$ uname -a
Linux avocat 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3~bpo70+1 (2016-07-07) x86_64 GNU/Linux
$ gdalbuildvrt --version
GDAL 2.1.1, released 2016/07/07
$ make
(... everything OK)
$ make test
(... several tests pass, until this one fails)
RUN: gdalbuildvrt -vrtnodata nan  testoutput/output_pair/dsm.vrt testoutput/outp
ut_pair/tiles_row_150_height_350/col_150_width_350/dsm.tif testoutput/output_pai
r/tiles_row_150_height_350/col_500_width_350/dsm.tif testoutput/output_pair/tile
s_row_500_height_350/col_150_width_350/dsm.tif testoutput/output_pair/tiles_row_
500_height_350/col_500_width_350/dsm.tif
0...10...20..*** glibc detected *** gdalbuildvrt: free(): invalid next size (nor
mal): 0x0000000001858ad0 ***

**Comment by dyoussef** [comment]
I never had this problem... We can try to write the dsm with GDAL to solve it?
Can you test this feature ? https://github.com/dyoussef/s2p/tree/feature_plyflatten_gdal

**Comment by mnhrdt** [comment]
the gdal version works OK, but since this error only happens (so far) on a single computer, where gdal was installed manually, i think it is better not to worry about that.

I'll close the issue if nobody disagrees in a few days.

**Comment by dyoussef** [comment]
The gdal version works so I made the PR #94

**Comment by dyoussef** [comment]
Do we close the issue?
