### ISSUE TITLE
[Info] Height reference

### ISSUE THREAD

**Issue by learning4life** [MISS3D/s2p#89]
What is the height reference in the output DSM.tif and *.ply files?

I presume it’s the Ellipsoidal height in meters, but a EPSG reference would be very helpful.

Kind regards
Thomas

**Comment by carlodef** [comment]
The height reference in the output files is the one used in the input RPC camera model. Usually it's the Ellipsoidal height in meters.

**Comment by learning4life** [comment]
Thank you for the clarification!

**Comment by lionlai1989** [comment]
Hi guys:
I am a newbie in GIS, so please bear with my newbie question. Now I have a DSM.tif from s2p pipeline. 
The height of certain point in this DSM.tif is 84 meters, and you can see from the color of this DSM.tif, the average height of this area is about 84 to 130 meters. Below is DSM.tif.
<img width="671" alt="screen shot 2018-11-28 at 5 38 58 pm" src="https://user-images.githubusercontent.com/5163329/49166887-89c46a80-f334-11e8-8a26-6f43d3f41edc.png">

However, I use QGIS3 plugin SRTM downloader to download a map within this area. And the average height of this area is only 45 meters. Below is SRTM model.
<img width="880" alt="screen shot 2018-11-28 at 5 42 53 pm" src="https://user-images.githubusercontent.com/5163329/49167157-1a02af80-f335-11e8-990d-45098b088fe2.png">

My question is why is this happening? Is there a height translation between this two model?

I dive into the input RPC.XML file, but not really understand it. Here is the RPC.XML. According to previous discussions, the answer should lie in this PRX.XML. I found `<HEIGHT_SCALE>75</HEIGHT_SCALE> <HEIGHT_OFF>125</HEIGHT_OFF>`. What does it mean? Does it mean that the height difference of the lowest point and the highest point is 75 meters in this image. And the lowest point in this image is 125 meters of Ellipsoidal height. If this is true, then how do I combine the height values of these two model to get a more accountable result?
`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Dimap_Document>
  <Metadata_Identification>
    <METADATA_FORMAT version="2.15">DIMAP</METADATA_FORMAT>
    <METADATA_PROFILE>PHR_SENSOR</METADATA_PROFILE>
    <METADATA_SUBPROFILE>RPC</METADATA_SUBPROFILE>
    <METADATA_LANGUAGE>en</METADATA_LANGUAGE>
  </Metadata_Identification>
  <Rational_Function_Model>
    <Resource_Reference>
      <RESOURCE_TITLE version="2.1">NITF</RESOURCE_TITLE>
      <RESOURCE_ID>RPC00B</RESOURCE_ID>
    </Resource_Reference>
    <Global_RFM>
      <Direct_Model>
        <SAMP_NUM_COEFF_1>-0.000746138303839824</SAMP_NUM_COEFF_1>
        <SAMP_NUM_COEFF_2>0.992974383138236</SAMP_NUM_COEFF_2>
        <SAMP_NUM_COEFF_3>-0.00136806191864779</SAMP_NUM_COEFF_3>
        <SAMP_NUM_COEFF_4>-0.00542589306701223</SAMP_NUM_COEFF_4>
        <SAMP_NUM_COEFF_5>0.000380892259008059</SAMP_NUM_COEFF_5>
        <SAMP_NUM_COEFF_6>-5.74617679275689e-05</SAMP_NUM_COEFF_6>
        <SAMP_NUM_COEFF_7>-3.08031723565177e-05</SAMP_NUM_COEFF_7>
        <SAMP_NUM_COEFF_8>0.00144787088325648</SAMP_NUM_COEFF_8>
        <SAMP_NUM_COEFF_9>-0.000917301854509243</SAMP_NUM_COEFF_9>
        <SAMP_NUM_COEFF_10>-2.47260537856052e-07</SAMP_NUM_COEFF_10>
        <SAMP_NUM_COEFF_11>3.00785886729071e-08</SAMP_NUM_COEFF_11>
        <SAMP_NUM_COEFF_12>4.26418350526853e-06</SAMP_NUM_COEFF_12>
        <SAMP_NUM_COEFF_13>1.0213526565629e-06</SAMP_NUM_COEFF_13>
        <SAMP_NUM_COEFF_14>6.71319472379755e-07</SAMP_NUM_COEFF_14>
        <SAMP_NUM_COEFF_15>9.25019008588922e-06</SAMP_NUM_COEFF_15>
        <SAMP_NUM_COEFF_16>-4.06204414696598e-05</SAMP_NUM_COEFF_16>
        <SAMP_NUM_COEFF_17>-2.29503833731854e-09</SAMP_NUM_COEFF_17>
        <SAMP_NUM_COEFF_18>-2.86151604858025e-08</SAMP_NUM_COEFF_18>
        <SAMP_NUM_COEFF_19>1.03644166473121e-07</SAMP_NUM_COEFF_19>
        <SAMP_NUM_COEFF_20>-3.84559434550503e-09</SAMP_NUM_COEFF_20>
        <SAMP_DEN_COEFF_1>1</SAMP_DEN_COEFF_1>
        <SAMP_DEN_COEFF_2>-0.000696601983816332</SAMP_DEN_COEFF_2>
        <SAMP_DEN_COEFF_3>-0.000380754439664754</SAMP_DEN_COEFF_3>
        <SAMP_DEN_COEFF_4>5.29662944529877e-05</SAMP_DEN_COEFF_4>
        <SAMP_DEN_COEFF_5>-8.99915989770518e-06</SAMP_DEN_COEFF_5>
        <SAMP_DEN_COEFF_6>4.79895154014135e-08</SAMP_DEN_COEFF_6>
        <SAMP_DEN_COEFF_7>-2.61985672394448e-08</SAMP_DEN_COEFF_7>
        <SAMP_DEN_COEFF_8>-1.19981423050896e-06</SAMP_DEN_COEFF_8>
        <SAMP_DEN_COEFF_9>-1.61566090602473e-06</SAMP_DEN_COEFF_9>
        <SAMP_DEN_COEFF_10>6.73896884452982e-07</SAMP_DEN_COEFF_10>
        <SAMP_DEN_COEFF_11>-4.62885660231331e-11</SAMP_DEN_COEFF_11>
        <SAMP_DEN_COEFF_12>-1.89932376294534e-08</SAMP_DEN_COEFF_12>
        <SAMP_DEN_COEFF_13>1.69367487391709e-09</SAMP_DEN_COEFF_13>
        <SAMP_DEN_COEFF_14>-1.47697514214026e-09</SAMP_DEN_COEFF_14>
        <SAMP_DEN_COEFF_15>-5.8667991292401e-08</SAMP_DEN_COEFF_15>
        <SAMP_DEN_COEFF_16>1.08547992213467e-07</SAMP_DEN_COEFF_16>
        <SAMP_DEN_COEFF_17>-5.07494615699108e-10</SAMP_DEN_COEFF_17>
        <SAMP_DEN_COEFF_18>2.80093273936124e-10</SAMP_DEN_COEFF_18>
        <SAMP_DEN_COEFF_19>-2.25911343768134e-10</SAMP_DEN_COEFF_19>
        <SAMP_DEN_COEFF_20>7.3824894362597e-11</SAMP_DEN_COEFF_20>
        <LINE_NUM_COEFF_1>0.00360103691895295</LINE_NUM_COEFF_1>
        <LINE_NUM_COEFF_2>-0.0961658386279468</LINE_NUM_COEFF_2>
        <LINE_NUM_COEFF_3>-0.898976212270681</LINE_NUM_COEFF_3>
        <LINE_NUM_COEFF_4>0.00479249483595636</LINE_NUM_COEFF_4>
        <LINE_NUM_COEFF_5>-0.00140329539200166</LINE_NUM_COEFF_5>
        <LINE_NUM_COEFF_6>1.16588473850804e-05</LINE_NUM_COEFF_6>
        <LINE_NUM_COEFF_7>2.38050138265085e-05</LINE_NUM_COEFF_7>
        <LINE_NUM_COEFF_8>-0.000584324160588339</LINE_NUM_COEFF_8>
        <LINE_NUM_COEFF_9>-0.00194987294808321</LINE_NUM_COEFF_9>
        <LINE_NUM_COEFF_10>-2.47789243082852e-08</LINE_NUM_COEFF_10>
        <LINE_NUM_COEFF_11>1.92459233140694e-07</LINE_NUM_COEFF_11>
        <LINE_NUM_COEFF_12>-2.39031311201064e-06</LINE_NUM_COEFF_12>
        <LINE_NUM_COEFF_13>-1.10728594750913e-05</LINE_NUM_COEFF_13>
        <LINE_NUM_COEFF_14>-7.00406338414866e-07</LINE_NUM_COEFF_14>
        <LINE_NUM_COEFF_15>-8.98842890708345e-06</LINE_NUM_COEFF_15>
        <LINE_NUM_COEFF_16>-3.0731198083626e-05</LINE_NUM_COEFF_16>
        <LINE_NUM_COEFF_17>-6.54599231060754e-06</LINE_NUM_COEFF_17>
        <LINE_NUM_COEFF_18>1.34260407079084e-07</LINE_NUM_COEFF_18>
        <LINE_NUM_COEFF_19>8.29342598728098e-08</LINE_NUM_COEFF_19>
        <LINE_NUM_COEFF_20>3.50270096273584e-08</LINE_NUM_COEFF_20>
        <LINE_DEN_COEFF_1>1</LINE_DEN_COEFF_1>
        <LINE_DEN_COEFF_2>-0.000971451439197196</LINE_DEN_COEFF_2>
        <LINE_DEN_COEFF_3>0.00134925212856526</LINE_DEN_COEFF_3>
        <LINE_DEN_COEFF_4>5.26296857183859e-06</LINE_DEN_COEFF_4>
        <LINE_DEN_COEFF_5>-3.20077365776687e-06</LINE_DEN_COEFF_5>
        <LINE_DEN_COEFF_6>1.04134879112501e-07</LINE_DEN_COEFF_6>
        <LINE_DEN_COEFF_7>-2.23177317219708e-08</LINE_DEN_COEFF_7>
        <LINE_DEN_COEFF_8>2.54808063989682e-06</LINE_DEN_COEFF_8>
        <LINE_DEN_COEFF_9>-1.11366452756127e-05</LINE_DEN_COEFF_9>
        <LINE_DEN_COEFF_10>7.27291705678484e-06</LINE_DEN_COEFF_10>
        <LINE_DEN_COEFF_11>-5.11702238239715e-10</LINE_DEN_COEFF_11>
        <LINE_DEN_COEFF_12>-5.2784131503655e-08</LINE_DEN_COEFF_12>
        <LINE_DEN_COEFF_13>-3.54928436885734e-07</LINE_DEN_COEFF_13>
        <LINE_DEN_COEFF_14>-1.70274177947048e-08</LINE_DEN_COEFF_14>
        <LINE_DEN_COEFF_15>-3.38525662104838e-08</LINE_DEN_COEFF_15>
        <LINE_DEN_COEFF_16>-1.22581541433828e-07</LINE_DEN_COEFF_16>
        <LINE_DEN_COEFF_17>-6.25857967993536e-09</LINE_DEN_COEFF_17>
        <LINE_DEN_COEFF_18>1.24585036941696e-09</LINE_DEN_COEFF_18>
        <LINE_DEN_COEFF_19>4.12074023863858e-09</LINE_DEN_COEFF_19>
        <LINE_DEN_COEFF_20>1.54222469626184e-10</LINE_DEN_COEFF_20>
        <ERR_BIAS_X>8.509809638808654e-05</ERR_BIAS_X>
        <ERR_BIAS_Y>9.335568356701685e-05</ERR_BIAS_Y>
      </Direct_Model>
      <Inverse_Model>
        <SAMP_NUM_COEFF_1>0.000756856857605915</SAMP_NUM_COEFF_1>
        <SAMP_NUM_COEFF_2>1.00692083658256</SAMP_NUM_COEFF_2>
        <SAMP_NUM_COEFF_3>-0.00154047880467261</SAMP_NUM_COEFF_3>
        <SAMP_NUM_COEFF_4>0.00547096458171742</SAMP_NUM_COEFF_4>
        <SAMP_NUM_COEFF_5>0.000540526353842057</SAMP_NUM_COEFF_5>
        <SAMP_NUM_COEFF_6>4.1405909715653e-05</SAMP_NUM_COEFF_6>
        <SAMP_NUM_COEFF_7>-4.48728846573732e-05</SAMP_NUM_COEFF_7>
        <SAMP_NUM_COEFF_8>-0.00141930984291985</SAMP_NUM_COEFF_8>
        <SAMP_NUM_COEFF_9>0.00114168199450594</SAMP_NUM_COEFF_9>
        <SAMP_NUM_COEFF_10>4.264958737993e-07</SAMP_NUM_COEFF_10>
        <SAMP_NUM_COEFF_11>2.91790228524865e-07</SAMP_NUM_COEFF_11>
        <SAMP_NUM_COEFF_12>4.60398789970182e-07</SAMP_NUM_COEFF_12>
        <SAMP_NUM_COEFF_13>-1.44186819961223e-05</SAMP_NUM_COEFF_13>
        <SAMP_NUM_COEFF_14>-1.50394314195192e-06</SAMP_NUM_COEFF_14>
        <SAMP_NUM_COEFF_15>6.72803521920308e-06</SAMP_NUM_COEFF_15>
        <SAMP_NUM_COEFF_16>-5.39635897796296e-05</SAMP_NUM_COEFF_16>
        <SAMP_NUM_COEFF_17>5.15710361782022e-10</SAMP_NUM_COEFF_17>
        <SAMP_NUM_COEFF_18>-1.78955172196273e-07</SAMP_NUM_COEFF_18>
        <SAMP_NUM_COEFF_19>6.0490939093379e-07</SAMP_NUM_COEFF_19>
        <SAMP_NUM_COEFF_20>-7.85211806486908e-09</SAMP_NUM_COEFF_20>
        <SAMP_DEN_COEFF_1>1</SAMP_DEN_COEFF_1>
        <SAMP_DEN_COEFF_2>0.000667664728960558</SAMP_DEN_COEFF_2>
        <SAMP_DEN_COEFF_3>-0.000541018796097441</SAMP_DEN_COEFF_3>
        <SAMP_DEN_COEFF_4>-4.59072926461328e-05</SAMP_DEN_COEFF_4>
        <SAMP_DEN_COEFF_5>-7.03677854987924e-06</SAMP_DEN_COEFF_5>
        <SAMP_DEN_COEFF_6>1.30776276037896e-07</SAMP_DEN_COEFF_6>
        <SAMP_DEN_COEFF_7>-2.58708477024965e-07</SAMP_DEN_COEFF_7>
        <SAMP_DEN_COEFF_8>-2.30202392964842e-06</SAMP_DEN_COEFF_8>
        <SAMP_DEN_COEFF_9>1.23406878914671e-05</SAMP_DEN_COEFF_9>
        <SAMP_DEN_COEFF_10>-1.50382571042063e-06</SAMP_DEN_COEFF_10>
        <SAMP_DEN_COEFF_11>-3.80618499014433e-10</SAMP_DEN_COEFF_11>
        <SAMP_DEN_COEFF_12>-1.89418545228374e-09</SAMP_DEN_COEFF_12>
        <SAMP_DEN_COEFF_13>-1.03762627797018e-07</SAMP_DEN_COEFF_13>
        <SAMP_DEN_COEFF_14>-2.87520228902415e-09</SAMP_DEN_COEFF_14>
        <SAMP_DEN_COEFF_15>7.57304211680357e-08</SAMP_DEN_COEFF_15>
        <SAMP_DEN_COEFF_16>-3.77636404129356e-07</SAMP_DEN_COEFF_16>
        <SAMP_DEN_COEFF_17>1.52464132095325e-09</SAMP_DEN_COEFF_17>
        <SAMP_DEN_COEFF_18>-6.90238524001426e-10</SAMP_DEN_COEFF_18>
        <SAMP_DEN_COEFF_19>3.85230372863794e-09</SAMP_DEN_COEFF_19>
        <SAMP_DEN_COEFF_20>1.32462143998201e-10</SAMP_DEN_COEFF_20>
        <LINE_NUM_COEFF_1>0.00392470722200652</LINE_NUM_COEFF_1>
        <LINE_NUM_COEFF_2>-0.107713117271978</LINE_NUM_COEFF_2>
        <LINE_NUM_COEFF_3>-1.11219087598856</LINE_NUM_COEFF_3>
        <LINE_NUM_COEFF_4>0.00474577982559303</LINE_NUM_COEFF_4>
        <LINE_NUM_COEFF_5>0.000800891483848716</LINE_NUM_COEFF_5>
        <LINE_NUM_COEFF_6>-3.71094084150149e-06</LINE_NUM_COEFF_6>
        <LINE_NUM_COEFF_7>1.26448106825261e-05</LINE_NUM_COEFF_7>
        <LINE_NUM_COEFF_8>-0.000427686677057257</LINE_NUM_COEFF_8>
        <LINE_NUM_COEFF_9>-0.00272299111915185</LINE_NUM_COEFF_9>
        <LINE_NUM_COEFF_10>-1.03301587229142e-07</LINE_NUM_COEFF_10>
        <LINE_NUM_COEFF_11>-8.0927193556137e-08</LINE_NUM_COEFF_11>
        <LINE_NUM_COEFF_12>1.01201629776652e-06</LINE_NUM_COEFF_12>
        <LINE_NUM_COEFF_13>3.51586494271183e-06</LINE_NUM_COEFF_13>
        <LINE_NUM_COEFF_14>1.13001042822277e-06</LINE_NUM_COEFF_14>
        <LINE_NUM_COEFF_15>5.2259569351849e-06</LINE_NUM_COEFF_15>
        <LINE_NUM_COEFF_16>3.14124650425575e-05</LINE_NUM_COEFF_16>
        <LINE_NUM_COEFF_17>1.16851585563268e-05</LINE_NUM_COEFF_17>
        <LINE_NUM_COEFF_18>-3.1173938027102e-08</LINE_NUM_COEFF_18>
        <LINE_NUM_COEFF_19>-2.35553382355978e-07</LINE_NUM_COEFF_19>
        <LINE_NUM_COEFF_20>-4.9580187664102e-08</LINE_NUM_COEFF_20>
        <LINE_DEN_COEFF_1>1</LINE_DEN_COEFF_1>
        <LINE_DEN_COEFF_2>0.00126740335618694</LINE_DEN_COEFF_2>
        <LINE_DEN_COEFF_3>0.00142273722715955</LINE_DEN_COEFF_3>
        <LINE_DEN_COEFF_4>-4.96037608396756e-06</LINE_DEN_COEFF_4>
        <LINE_DEN_COEFF_5>5.48028723644555e-06</LINE_DEN_COEFF_5>
        <LINE_DEN_COEFF_6>4.80429387478925e-08</LINE_DEN_COEFF_6>
        <LINE_DEN_COEFF_7>-4.83332569967243e-07</LINE_DEN_COEFF_7>
        <LINE_DEN_COEFF_8>-7.86209950109183e-06</LINE_DEN_COEFF_8>
        <LINE_DEN_COEFF_9>3.08893591052912e-05</LINE_DEN_COEFF_9>
        <LINE_DEN_COEFF_10>-1.05166695122597e-05</LINE_DEN_COEFF_10>
        <LINE_DEN_COEFF_11>-2.15970912037853e-09</LINE_DEN_COEFF_11>
        <LINE_DEN_COEFF_12>-7.29523014468501e-09</LINE_DEN_COEFF_12>
        <LINE_DEN_COEFF_13>1.32348702827656e-07</LINE_DEN_COEFF_13>
        <LINE_DEN_COEFF_14>-2.32089816628957e-08</LINE_DEN_COEFF_14>
        <LINE_DEN_COEFF_15>1.49863686043936e-07</LINE_DEN_COEFF_15>
        <LINE_DEN_COEFF_16>1.2694837691175e-07</LINE_DEN_COEFF_16>
        <LINE_DEN_COEFF_17>1.14381789621783e-08</LINE_DEN_COEFF_17>
        <LINE_DEN_COEFF_18>-4.07547273311536e-10</LINE_DEN_COEFF_18>
        <LINE_DEN_COEFF_19>-3.87187056707755e-09</LINE_DEN_COEFF_19>
        <LINE_DEN_COEFF_20>3.42740071591094e-11</LINE_DEN_COEFF_20>
        <ERR_BIAS_ROW>0.0002748236021640053</ERR_BIAS_ROW>
        <ERR_BIAS_COL>0.0002898099283047482</ERR_BIAS_COL>
      </Inverse_Model>
      <RFM_Validity>
        <Direct_Model_Validity_Domain>
            <FIRST_ROW>1</FIRST_ROW>
            <FIRST_COL>1</FIRST_COL>
            <LAST_ROW>19041</LAST_ROW>
            <LAST_COL>16133</LAST_COL>
          </Direct_Model_Validity_Domain>
        <Inverse_Model_Validity_Domain>
            <FIRST_LON>6.721400750431096</FIRST_LON>
            <FIRST_LAT>51.15814961002613</FIRST_LAT>
            <LAST_LON>6.883648372530217</LAST_LON>
            <LAST_LAT>51.27337653171568</LAST_LAT>
          </Inverse_Model_Validity_Domain>
        <LONG_SCALE>0.06903594852626016</LONG_SCALE>
        <LONG_OFF>6.802429273130057</LONG_OFF>
        <LAT_SCALE>0.05648378514193553</LAT_SCALE>
        <LAT_OFF>51.2157630708709</LAT_OFF>
        <HEIGHT_SCALE>75</HEIGHT_SCALE>
        <HEIGHT_OFF>125</HEIGHT_OFF>
        <SAMP_SCALE>8066</SAMP_SCALE>
        <SAMP_OFF>8067</SAMP_OFF>
        <LINE_SCALE>9519.999999999998</LINE_SCALE>
        <LINE_OFF>9520.999999999998</LINE_OFF>
      </RFM_Validity>
    </Global_RFM>
  </Rational_Function_Model>
</Dimap_Document>
`

Any help would be appreciated.
Best Regards,
