### ISSUE TITLE
"s2p_test.py --all" return dsm.tif error

### ISSUE THREAD

**Issue by learning4life** [MISS3D/s2p#96]
I am unable to make the new build (963a429) work on my Ubuntu 16.04 system. 
The "python s2p_test.py --all" return an error and dsm.tif is not build.

Error code appended below:

python s2p_test.py --all
The following tests will be run: ['unit_image_keypoints', 'unit_matching', 'unit_matches_from_rpc', 'end2end_pair', 'end2end_triplet', 'end2end_cluster', 'unit_distributed_plyflatten']
Running test unit_image_keypoints...

RUN: sift_roi testdata/input_triplet/img_02.tif 100 100 200 200  -o /tmp/s2p_eABiuO.txt
0:00:00.224520
144 spatially redundant kpts found in test
144 spatially redundant kpts found in ref
48 kpts found in test but not in ref
48 kpts found in ref but not in test
0 test kpts have no spatially close match in ref
0 ref kpts have no spatially close match in test
Success.

Running test unit_matching...

RUN: matching testdata/units/sift1.txt testdata/units/sift2.txt -relative 0.600000 -o /tmp/s2p_xXQwcN.txt
199 matches
0:00:00.216111
Success.

Running test unit_matches_from_rpc...

WARNING: returning coarse range from rpc
Success.

Running test end2end_pair...

Configuration file:  testdata/input_pair/config.json
Reference DSM: testdata/expected_output/pair/dsm.tif 

WARNING: ignoring unknown parameter utm_bbx.
tile size: 350 350
total number of tiles: 4 (2 x 2)

discarding masked tiles...
done 4 / 4 tiles
Elapsed time: 0:00:00.111502

correcting pointing locally...
done 4 / 4 tiles
Elapsed time: 0:00:04.158609

correcting pointing globally...
Elapsed time: 0:00:00.002597

rectifying tiles...
done 4 / 4 tiles
Elapsed time: 0:00:00.308419

running stereo matching...
done 4 / 4 tiles
Elapsed time: 0:00:09.623242

triangulating tiles...
done 4 / 4 tiles
Elapsed time: 0:00:00.507609

computing global source window (xoff, yoff, xsize, ysize)...
Elapsed time: 0:00:00.000363

computing DSM by tile...
done 4 / 4 tiles
Elapsed time: 0:00:00.205335

computing global DSM...

RUN: gdalbuildvrt -vrtnodata nan  testoutput/output_pair/dsm.vrt testoutput/output_pair/tiles_row_150_height_350/col_150_width_350/dsm.tif testoutput/output_pair/tiles_row_150_height_350/col_500_width_350/dsm.tif testoutput/output_pair/tiles_row_500_height_350/col_150_width_350/dsm.tif testoutput/output_pair/tiles_row_500_height_350/col_500_width_350/dsm.tif
ERROR 5: Invalid -vrtnodata value
Traceback (most recent call last):
  File "s2p_test.py", line 287, in <module>
    command(*args)
  File "s2p_test.py", line 167, in end2end
    s2p.main(test_cfg)
  File "/home/dem/s2p/s2p.py", line 638, in main
    global_dsm(tiles)
  File "/home/dem/s2p/s2p.py", line 508, in global_dsm
    " ".join(dsm_list)))
  File "/home/dem/s2p/s2plib/common.py", line 97, in run
    e.output})
s2plib.common.RunFailure: {'environment': {'QT_QPA_PLATFORMTHEME': 'appmenu-qt5', 'IM_CONFIG_PHASE': '1', 'DBUS_STARTER_ADDRESS': 'unix:abstract=/tmp/dbus-pB2Fc4nwiv,guid=50942473b3d9100fe651f84c58d94289', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'UPSTART_EVENTS': 'starting', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'XDG_SESSION_TYPE': 'x11', 'QT_IM_MODULE': 'ibus', 'LOGNAME': 'dem', 'USER': 'dem', 'PATH': '/home/dem/s2p/bin:/home/dem/bin:/home/dem/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin', 'XDG_VTNR': '7', 'GNOME_KEYRING_CONTROL': '', 'DISPLAY': ':0', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'XDG_SESSION_PATH': '/org/freedesktop/DisplayManager/Session0', 'XAUTHORITY': '/home/dem/.Xauthority', 'LANGUAGE': 'en_US:en', 'SESSION_MANAGER': 'local/dem-pc:@/tmp/.ICE-unix/1921,unix/dem-pc:/tmp/.ICE-unix/1921', 'SHLVL': '1', 'QT_LINUX_ACCESSIBILITY_ALWAYS_ON': '1', 'XDG_GREETER_DATA_DIR': '/var/lib/lightdm-data/dem', 'CLUTTER_IM_MODULE': 'xim', 'UPSTART_INSTANCE': '', 'QT_ACCESSIBILITY': '1', 'WINDOWID': '54525962', 'SESSIONTYPE': 'gnome-session', 'XMODIFIERS': '@im', 'GPG_AGENT_INFO': '/home/dem/.gnupg/S.gpg-agent:0:1', 'HOME': '/home/dem', 'QT4_IM_MODULE': 'xim', 'GTK2_MODULES': 'overlay-scrollbar', 'XDG_SESSION_DESKTOP': 'ubuntu', 'XDG_RUNTIME_DIR': '/run/user/1000', 'INSTANCE': '', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'COMPIZ_CONFIG_PROFILE': 'ubuntu', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'VTE_VERSION': '4205', 'GDMSESSION': 'ubuntu', 'MANDATORY_PATH': '/usr/share/gconf/ubuntu.mandatory.path', 'UPSTART_JOB': 'dbus', 'GNOME_KEYRING_PID': '', 'XDG_SEAT_PATH': '/org/freedesktop/DisplayManager/Seat0', 'DBUS_STARTER_BUS_TYPE': 'session', 'XDG_CURRENT_DESKTOP': 'Unity', 'XDG_SESSION_ID': 'c1', 'DBUS_SESSION_BUS_ADDRESS': 'unix:abstract=/tmp/dbus-pB2Fc4nwiv,guid=50942473b3d9100fe651f84c58d94289', '_': '/usr/bin/python', 'DEFAULTS_PATH': '/usr/share/gconf/ubuntu.default.path', 'GTK_IM_MODULE': 'ibus', 'DESKTOP_SESSION': 'ubuntu', 'UPSTART_SESSION': 'unix:abstract=/com/ubuntu/upstart-session/1000/1406', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/usr/share/upstart/xdg:/etc/xdg', 'GTK_MODULES': 'gail:atk-bridge:unity-gtk-module', 'OLDPWD': '/home/dem', 'GDM_LANG': 'en_US', 'DBUS_DEBUG_OUTPUT': '1', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop', 'PWD': '/home/dem/s2p', 'JOB': 'xsession-init', 'XDG_MENU_PREFIX': 'gnome-', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'XDG_SEAT': 'seat0'}, 'output': None, 'command': u'gdalbuildvrt -vrtnodata nan  testoutput/output_pair/dsm.vrt testoutput/output_pair/tiles_row_150_height_350/col_150_width_350/dsm.tif testoutput/output_pair/tiles_row_150_height_350/col_500_width_350/dsm.tif testoutput/output_pair/tiles_row_500_height_350/col_150_width_350/dsm.tif testoutput/output_pair/tiles_row_500_height_350/col_500_width_350/dsm.tif'}

**Comment by carlodef** [comment]
This is probably due to the version of gdal installed on your system. The command `gdalbuildvrt -vrtnodata nan testoutput/output_pair/dsm.vrt ` requires gdal >= 2.1

Could you run `gdal-config --version` to check your gdal version? If older than 2.1, could you update it and try again?

**Comment by learning4life** [comment]
Updating gdal to 2.1.0 fixed my error :)
