### ISSUE TITLE
msmw/sgbm error and Config.json settings question

### ISSUE THREAD

**Issue by learning4life** [MISS3D/s2p#97]
I am not sure I set up my Config.json settings optimally using WV-2 in-orbit stereo imagery covering an urban area. [Config.json appended](https://www.dropbox.com/s/942cqd1drrgwhpj/hillerod.json?dl=0).

I get output using stereo matching algorithm "mgm" and "tvl1". But with mixed results when compared with a master LiDAR DSM.
Stereo matching algorithm "[sgbm](https://www.dropbox.com/s/19jh2ydykd94ndn/sgbm_error.txt?dl=0)" and "[msmw](https://www.dropbox.com/s/cxplouvnj26xcpi/msmw_error.txt?dl=0)" return error. Terminal error log included in link.

Any guidance to improve settings is very welcome.

**Comment by learning4life** [comment]
Links fixed.

**Comment by carlodef** [comment]
Did you compile the `sgbm` and `msmw` targets by running `make all` in `s2p` root directory?

**Comment by learning4life** [comment]
By running `make all` in `s2p` root directory the "sgbm" returned a output.

But "[msmw](https://www.dropbox.com/s/5vweuosaff9fv74/Terminal_error_msmw.txt?dl=0)" and "[hirschmuller08](https://www.dropbox.com/s/tfqifsqcni75s7e/Terminal_error_hirschmuller08.txt?dl=0)" did not.

**Comment by carlodef** [comment]
Could run `iip_stereo_correlation_multi_win2 -i 1 -n 4 -p 4 -W 5 -x 9 -y 9 -r 1 -d 1 -t -1 -s 0 -b 0 -o 0.25 -f 0 -P 32 -m -10 -M 15 Hilleroedoutput/tiles_row_27175_height_750/col_35180_width_625/pair_1/rectified_ref.tif Hilleroedoutput/tiles_row_27175_height_750/col_35180_width_625/pair_1/rectified_sec.tif Hilleroedoutput/tiles_row_27175_height_750/col_35180_width_625/pair_1/rectified_disp.tif Hilleroedoutput/tiles_row_27175_height_750/col_35180_width_625/pair_1/rectified_mask.png` separately and share its output ?

**Comment by learning4life** [comment]
Output: `iip_stereo_correlation_multi_win2: command not found`

**Comment by carlodef** [comment]
`iip_stereo_correlation_multi_win2` should be located in the `s2p/bin` directory. Is it there? If yes can you retry with its path?

**Comment by learning4life** [comment]
No, `iip_stereo_correlation_multi_win2` is not in my `s2p/bin` directory but `iip_stereo_correlation_multi_win2.cpp` is in `s2p/3rdparty/msmw2/libstereo_newversion` and `s2p/3rdparty/msmw/libstereo`.
